### ISSUE TITLE
error after checkout to first commit after having a commit with big file

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-version-control#4]
The produced error is:

`First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object. at Function.Buffer.from (buffer.js:183:11) at documentModel.entitySets.(anonymous function).entityType.documentProperties.forEach (/Volumes/DATA/workspace/jsreport-v2-with-version-control-test/node_modules/jsreport-version-control/lib/patches.js:69:23) at Array.forEach () at module.exports.createPatch (/Volumes/DATA/workspace/jsreport-v2-with-version-control-test/node_modules/jsreport-version-control/lib/patches.js:42:69) at commitToDiff.changes.reduce (/Volumes/DATA/workspace/jsreport-v2-with-version-control-test/node_modules/jsreport-version-control/lib/versionControl.js:170:19) at Array.reduce () at Object.diff (/Volumes/DATA/workspace/jsreport-v2-with-version-control-test/node_modules/jsreport-version-control/lib/versionControl.js:160:35) at`

the steps to reproduce it are:

- do a first commit with some entities
- create a new template and do a commit,
- then import this file 
[export-template-with-image.zip](https://github.com/jsreport/jsreport-version-control/files/2384524/export-template-with-image.zip) and do a commit (it contains an image that is big enough that it does not show in diff)
- finally go to commit history and try to checkout the first commit, after that page is reloaded and when you try to open the "Commit" tabs the error is throw

**Comment by pofider** [comment]
fixed in https://github.com/jsreport/jsreport-version-control/commit/e3697a0446d7ab4627606cc8d9a15f2bff3e4b6e
